[project]
name = "national-idocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "imutils>=0.5.4",
    "numpy>=2.5.3",
    "paddleocr==3.3.3",
    "paddlepaddle==3.2.2",
    "streamlit>=1.64.0",
    "torch==2.14.0",
]
